{% set name = "asn1" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7591aa0617c828c31a855dd0218114cf543b2a8e99583a439bbcd3fe8f18ea9a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - asn1

about:
  home: https://github.com/andrivet/python-asn1
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python-ASN1 is a simple ASN.1 encoder and decoder for Python 2.6+ and 3.3+.
  doc_url: https://python-asn1.readthedocs.io/en/latest/
  dev_url: https://github.com/andrivet/python-asn1

extra:
  recipe-maintainers:
    - chrisburr
