travis:
  secure:
    BINSTAR_TOKEN: rjBsZf0dQw6zIoL5nF+MRaE/a2xhG+Por+l+UyP6tDbBppKecVfeK9YWIHHEcF8y8LTth+tbh2cUfaeeIrlkStctdeZl/4nWDEmGrLzTrD/WahSyePYPjJ9PzpdPNd2jiXpW87Sn+f7Oat6Be/A3V88y/UeeTK6uMzwV2uFBQcEFA34wcfSjiMibOmZEH1CcSpKroOILmupuGD0rPglxrBfgHWvx9FILrQ7B9P3bG8KNC/yd7toRwHYiqfjiLy3GykpqER0fVSbmoBUeme4FgkTL0rQOEkfzs1VuBqULOjb+PVbR3MZYrH7JDGmsAIBoL1aC3DsTwtuBosZzh/fCaimaMcfi3H9/kxE4206wiqbwWTlcj9kXsxNJ/Urv9KY4ue37LnjZe/WPSSpatXkaEj1pXDX20wTL7DrN38sj9LWMb5loo4gEHVV8hQQTPR8LTunXLbeOC2NyBmIijzSdmrqQjj7jzaxJnGbfjePAsDxwQSjgf67hzyXmwhwviuiuEl9RZ6kOXqbyJtXbbvGD7KTquVoVciLfU3ZODues+M0eU4wt/UUri0aGw2ahVGFOjRFZtR0jafw48Bo2woO4BejfAxvjHJui95WxYKgz0OWYGhqIELAMgvp6R+I8Nagra30QjFi1ubz0cMuBy1Ht4rgH5IjHE2bO0gjFPh0Pxkc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
